require ("util")
require ("prototypes.smart-car-prototypes")
require ("prototypes.smart-car-terrain-prototypes")
require ("prototypes.smart-car-road-prototypes")
require ("prototypes.smart-car-digits-prototypes")
